//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegendsOfKesmaiSurvival.WinFormsClient.MatchMaking {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LegendsOfKesmaiSurvival.Services.MatchMaking", ConfigurationName="MatchMaking.IMatchMakingService", CallbackContract=typeof(LegendsOfKesmaiSurvival.WinFormsClient.MatchMaking.IMatchMakingServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IMatchMakingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="LegendsOfKesmaiSurvival.Services.MatchMaking/IMatchMakingService/Join", ReplyAction="LegendsOfKesmaiSurvival.Services.MatchMaking/IMatchMakingService/JoinResponse")]
        void Join(System.Guid key);
        
        [System.ServiceModel.OperationContractAttribute(Action="LegendsOfKesmaiSurvival.Services.MatchMaking/IMatchMakingService/Leave", ReplyAction="LegendsOfKesmaiSurvival.Services.MatchMaking/IMatchMakingService/LeaveResponse")]
        void Leave(System.Guid key);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="LegendsOfKesmaiSurvival.Services.MatchMaking/IMatchMakingService/StartNewGame")]
        void StartNewGame(System.Guid key);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="LegendsOfKesmaiSurvival.Services.MatchMaking/IMatchMakingService/JoinGame")]
        void JoinGame(System.Guid key, System.Guid serverId);
        
        [System.ServiceModel.OperationContractAttribute(Action="LegendsOfKesmaiSurvival.Services.MatchMaking/IMatchMakingService/GetActiveGameLis" +
            "t", ReplyAction="LegendsOfKesmaiSurvival.Services.MatchMaking/IMatchMakingService/GetActiveGameLis" +
            "tResponse")]
        System.Guid[] GetActiveGameList(System.Guid key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchMakingServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="LegendsOfKesmaiSurvival.Services.MatchMaking/IMatchMakingService/JoinedGameCallba" +
            "ck")]
        void JoinedGameCallback(LegendsOfKesmaiSurvival.Core.GameStateInformation.ServerInstanceInformation serverInstanceInformation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchMakingServiceChannel : LegendsOfKesmaiSurvival.WinFormsClient.MatchMaking.IMatchMakingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchMakingServiceClient : System.ServiceModel.DuplexClientBase<LegendsOfKesmaiSurvival.WinFormsClient.MatchMaking.IMatchMakingService>, LegendsOfKesmaiSurvival.WinFormsClient.MatchMaking.IMatchMakingService {
        
        public MatchMakingServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MatchMakingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MatchMakingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchMakingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchMakingServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Join(System.Guid key) {
            base.Channel.Join(key);
        }
        
        public void Leave(System.Guid key) {
            base.Channel.Leave(key);
        }
        
        public void StartNewGame(System.Guid key) {
            base.Channel.StartNewGame(key);
        }
        
        public void JoinGame(System.Guid key, System.Guid serverId) {
            base.Channel.JoinGame(key, serverId);
        }
        
        public System.Guid[] GetActiveGameList(System.Guid key) {
            return base.Channel.GetActiveGameList(key);
        }
    }
}
