//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegendsOfKesmaiSurvival.WinFormsClient.Authentication {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LegendsOfKesmaiSurvival.Services.Authentication", ConfigurationName="Authentication.IAuthenticationService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="LegendsOfKesmaiSurvival.Services.Authentication/IAuthenticationService/Login", ReplyAction="LegendsOfKesmaiSurvival.Services.Authentication/IAuthenticationService/LoginRespo" +
            "nse")]
        bool Login(out System.Guid key, string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="LegendsOfKesmaiSurvival.Services.Authentication/IAuthenticationService/GetService" +
            "Information", ReplyAction="LegendsOfKesmaiSurvival.Services.Authentication/IAuthenticationService/GetService" +
            "InformationResponse")]
        LegendsOfKesmaiSurvival.Core.GameStateInformation.ServiceInformation[] GetServiceInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="LegendsOfKesmaiSurvival.Services.Authentication/IAuthenticationService/CreateNewU" +
            "ser", ReplyAction="LegendsOfKesmaiSurvival.Services.Authentication/IAuthenticationService/CreateNewU" +
            "serResponse")]
        bool CreateNewUser(out string exception, string userName, string nickName, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticationServiceChannel : LegendsOfKesmaiSurvival.WinFormsClient.Authentication.IAuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServiceClient : System.ServiceModel.ClientBase<LegendsOfKesmaiSurvival.WinFormsClient.Authentication.IAuthenticationService>, LegendsOfKesmaiSurvival.WinFormsClient.Authentication.IAuthenticationService {
        
        public AuthenticationServiceClient() {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(out System.Guid key, string userName, string password) {
            return base.Channel.Login(out key, userName, password);
        }
        
        public LegendsOfKesmaiSurvival.Core.GameStateInformation.ServiceInformation[] GetServiceInformation() {
            return base.Channel.GetServiceInformation();
        }
        
        public bool CreateNewUser(out string exception, string userName, string nickName, string password) {
            return base.Channel.CreateNewUser(out exception, userName, nickName, password);
        }
    }
}
