//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegendsOfKesmaiSurvival.Services.ZombiesClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LegendsOfKesmaiSurvival.Services.Zombies", ConfigurationName="ZombiesClient.IGameplay", CallbackContract=typeof(LegendsOfKesmaiSurvival.Services.ZombiesClient.IGameplayCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IGameplay {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="LegendsOfKesmaiSurvival.Services.Zombies/IGameplay/Join")]
        void Join();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsInitiating=false, Action="LegendsOfKesmaiSurvival.Services.Zombies/IGameplay/SendChat")]
        void SendChat(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameplayCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="LegendsOfKesmaiSurvival.Services.Zombies/IGameplay/ChatReceivedCallback")]
        void ChatReceivedCallback(string text);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="LegendsOfKesmaiSurvival.Services.Zombies/IGameplay/GameStateUpdatedCallback")]
        void GameStateUpdatedCallback(LegendsOfKesmaiSurvival.Core.GameStateInformation.GameStateUpdate gameStateUpdate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameplayChannel : LegendsOfKesmaiSurvival.Services.ZombiesClient.IGameplay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameplayClient : System.ServiceModel.DuplexClientBase<LegendsOfKesmaiSurvival.Services.ZombiesClient.IGameplay>, LegendsOfKesmaiSurvival.Services.ZombiesClient.IGameplay {
        
        public GameplayClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameplayClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameplayClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameplayClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameplayClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Join() {
            base.Channel.Join();
        }
        
        public void SendChat(string text) {
            base.Channel.SendChat(text);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LegendsOfKesmaiSurvival.Services.Zombies", ConfigurationName="ZombiesClient.IAdministration", CallbackContract=typeof(LegendsOfKesmaiSurvival.Services.ZombiesClient.IAdministrationCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAdministration {
        
        [System.ServiceModel.OperationContractAttribute(Action="LegendsOfKesmaiSurvival.Services.Zombies/IAdministration/StartGame", ReplyAction="LegendsOfKesmaiSurvival.Services.Zombies/IAdministration/StartGameResponse")]
        void StartGame(string mapFile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministrationCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="LegendsOfKesmaiSurvival.Services.Zombies/IAdministration/Callback")]
        void Callback();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministrationChannel : LegendsOfKesmaiSurvival.Services.ZombiesClient.IAdministration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministrationClient : System.ServiceModel.DuplexClientBase<LegendsOfKesmaiSurvival.Services.ZombiesClient.IAdministration>, LegendsOfKesmaiSurvival.Services.ZombiesClient.IAdministration {
        
        public AdministrationClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AdministrationClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AdministrationClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdministrationClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdministrationClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void StartGame(string mapFile) {
            base.Channel.StartGame(mapFile);
        }
    }
}
